# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dot-properties/all/dot-properties.rbi
#
# dot-properties-0.1.3
class DotProperties
  def <<(item); end
  def [](key); end
  def []=(key, value); end
  def assemble(item); end
  def auto_expand; end
  def auto_expand=(arg0); end
  def compact!; end
  def decode(v); end
  def default_delimiter; end
  def default_delimiter=(arg0); end
  def delete(key); end
  def each(*args, &block); end
  def each_key(*args, &block); end
  def each_pair(*args, &block); end
  def each_value(*args, &block); end
  def empty?(*args, &block); end
  def encode(v); end
  def escape(v); end
  def fetch(*args, &block); end
  def find_key(key); end
  def get(key, expand = nil); end
  def has_key?(*args, &block); end
  def has_value?(*args, &block); end
  def include?(*args, &block); end
  def initialize(lines = nil); end
  def inspect; end
  def invert(*args, &block); end
  def key(*args, &block); end
  def key?(*args, &block); end
  def keys(*args, &block); end
  def length(*args, &block); end
  def member?(*args, &block); end
  def merge(*args, &block); end
  def normalize_delimiters!; end
  def reject(*args, &block); end
  def select(*args, &block); end
  def self.load(file); end
  def self.parse(str); end
  def set(key, value); end
  def size(*args, &block); end
  def strip_blanks!; end
  def strip_comments!; end
  def to_a; end
  def to_h; end
  def to_s; end
  def tokenize(item); end
  def unescape(v); end
  def value?(*args, &block); end
  def values(*args, &block); end
  def values_at(*args, &block); end
  extend Forwardable
end
