# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/marc-fastxmlwriter/all/marc-fastxmlwriter.rbi
#
# marc-fastxmlwriter-1.0.0
module Marc
end
module Marc::FastXMLWriter
end
module MARC
end
class MARC::FastXMLWriter < MARC::XMLWriter
  def initialize(file, opts = nil); end
  def self.encode(r, opts = nil); end
  def self.open_collection(use_ns); end
  def self.open_controlfield(tag); end
  def self.open_datafield(tag, ind1, ind2); end
  def self.open_subfield(code); end
  def self.single_record_document(r, opts = nil); end
  def write(record); end
end
