# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/scrub_rb/all/scrub_rb.rbi
#
# scrub_rb-1.0.1
module ScrubRb
  def self.scrub(str, replacement = nil, &block); end
  def self.scrub_replace(result, bad_chars, replacement, block); end
end
class String
end
